def P20241121_contact_test1():
  global _hidden_verificationVariable=0
  set_target_payload(1.500000, [0.001000, -0.003000, 0.050000], [0.003026, 0.003026, 0.003026, 0.000000, 0.000000, 0.000000])
  set_tcp(p[-1.7E-4,0.0,0.19294999999999998,0.0,0.0,0.0])
  set_tool_communication(True, 115200, 0, 1, 1.5, 3.5)
  set_tool_output_mode(0)
  set_tool_digital_output_mode(0, 1)
  set_tool_digital_output_mode(1, 1)
  set_tool_voltage(24)
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 1)
  set_analog_outputdomain(1, 0)
  set_input_actions_to_default()
  set_tool_digital_input_action(0, "freedrive")
  set_gravity([0.0, 0.0, 9.82])
  set_safety_mode_transition_hardness(0)
  global i_var_1=p[0.31, 0, 0, 0, 0, 0]
  global u24179u38754_1=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global u24179u38754_2=p[0.2,0.6,0.4,-1.4839444017850547,-0.07419722008925289,-2.225916602677581]
  global u24179u38754_3=p[0.1459477485431481,-0.10308445883660293,0.13857682671027435,-0.008977024873201634,0.014216906208388691,-2.4400986907073663]
  global u28857_1=p[0.10203918836050063,-0.5259531579406657,0.376430278847906,-0.18768520041296463,-3.1325095402283982,-0.09669790600413578]
  global u28857_2=p[0.0665007526844362,-0.3872123180436422,0.638459113340625,-0.320095108678139,-2.6903368475934015,1.4700117755369673]
  global u30452u32447_1=p[0.0,0.0,0.0,0.0,0.0,0.0]
  step_count_b4d2483f_8893_49b8_936f_64b158deedd3 = 0.0
  thread Step_Counter_Thread_a2b80ebc_5de6_4f94_bd03_a8c00072d35d():
    while (True):
      step_count_b4d2483f_8893_49b8_936f_64b158deedd3 = step_count_b4d2483f_8893_49b8_936f_64b158deedd3 + 1.0
      sync()
    end
  end
  run Step_Counter_Thread_a2b80ebc_5de6_4f94_bd03_a8c00072d35d()
  $ 24 "Thread_1"
  thread Thread_1():
    while (True):
      $ 25 "tmp≔p[0,0,0,0,0,0]"
      global tmp=p[0,0,0,0,0,0]
      $ 26 "循环"
      while (True):
        $ 27 "watchdog≔read_input_integer_register(0)"
        global watchdog=read_input_integer_register(0)
        $ 28 "脚本: pose_register.script"
        tmp[0]=read_input_float_register(0)
        tmp[1]=read_input_float_register(1)
        tmp[2]=read_input_float_register(2)
        tmp[3]=read_input_float_register(3)
        tmp[4]=read_input_float_register(4)
        tmp[5]=read_input_float_register(5)
        $ 29 "sync()"
        sync()
      end
    end
  end
  threadId_Thread_1 = run Thread_1()
  while (True):
    $ 2 "机器人程序"
    $ 3 "usb = rpc_factory('xmlrpc','http://192.168.1.3:9120/RPC2')"
    usb = rpc_factory("xmlrpc","http://192.168.1.3:9120/RPC2")
    $ 4 "usb.disEnableSlipDetector()"
    usb.disEnableSlipDetector()
    $ 5 "弹出窗口: place check everything is ok!"
    popup("place check everything is ok!", "消息", False, False, blocking=True)
    $ 6 "write_output_integer_register(0,1)"
    write_output_integer_register(0,1)
    $ 10 "usb.open()"
    usb.open()
    $ 11 "弹出窗口: close"
    popup("close", "消息", False, False, blocking=True)
    $ 12 "usb.adaptiveClose()"
    usb.adaptiveClose()
    $ 14 "等待: 2.0"
    sleep(2.0)
    $ 16 "usb.enableSlipDetector()"
    usb.enableSlipDetector()
    $ 17 "循环"
    while (True):
    end
  end
end
